permalink: /blog/:year/:month/:title.html 
include: ['.htaccess']
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "CNAME", "Gemfile", "Gemfile.lock"]
markdown: kramdown
highlights: pygments
url: YingmoWang.github.io
baseurl：/MNMTWebsite
lsi: false
safe: true
timezone: Asia/Shanghai
auto: false 

paginate: 8
paginate_path: "page:num"

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

JB :
  IMAGE_PATH : http://coolshell.info/images

# presonal config
domain: http://mnmt.xyz
title: Centre of Micro Nano Manufacturing Technology
description: Draw my life with code
author: Wangyingmo
email: wangyingmo@tju.edu.cn

config:
  js_dir:
  img_dir:
  css_dir:
